name: build-artifact-publish
on:
  push:
    tags:
      - "*"
jobs:
  build-matrix-publish:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x64, Win32]
        configuration: [Release, Debug]
    steps:
      - uses: actions/checkout@master
      - name: Build program
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_x86.bat"
          call msbuild -m:5 -nologo -p:Configuration="${{ matrix.configuration }}" -p:Platform="${{ matrix.platform }}"
          if %ERRORLEVEL%==1 exit %ERRORLEVEL%
          call release.bat ${{ matrix.configuration }} ${{ matrix.platform }}
      - name: Upload release    
        uses: marvinpinto/action-automatic-releases@master
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          title: ""
          automatic_release_tag: latest
          files: distribute/*.7z
